- type: department
  id: M14Hydra
  name: department-Hydra
  description: department-Hydra-description
  color: "#434d4c"
  roles:
  - M14HeadOfHydra
  - M14Minister
  - M14SoldierHydra

- type: department
  id: M14RedLine
  name: department-RedLine
  description: department-RedLine-description
  color: "#d40000"
  roles:
  - M14HeadOfRedLine
  - M14PolitHandRedLine
  - M14SoldierRedline

- type: department
  id: M14Hansa
  name: department-Hansa
  description: department-Hansa-description
  color: "#5d4c34"
  roles:
  - M14HeadOfHansa
  - M14TradeAgentHansa
  - M14OfficerHansa
  - M14CivilianHansa

- type: department
  id: M14Sparta
  name: department-Sparta
  description: department-Sparta-description
  color: "#1E90FF"
  roles:
  - M14HeadOfSparta
  - M14LieutenantOfHeadOfSparta
  - M14MedicSparta
  - M14SoldierSparta

- type: department
  id: M14Tech
  name: department-Tech
  description: department-Tech-description
  color: "#942954"
  roles:
  - M14HeadOfTech
  - M14SecurityTech
  - M14TechnicTech

- type: department
  id: M14VDNH
  name: department-VDNH
  description: department-VDNH-description
  color: "#f59628"
  roles:
  - M14HeadOfVDNH
  - M14SecurityVDNH
  - M14StalkerVDNH
